#!/usr/bin/env python3
"""Build offline players for timed slides and standalone animation review."""
from pathlib import Path
import json,os
ROOT=Path(__file__).resolve().parents[1]
story=json.loads((ROOT/'storyboard.json').read_text())
manifest=json.loads((ROOT/'animation_manifest.json').read_text())
total=story['total_duration_seconds'];duration_label=f'{total//60}:{total%60:02d}'
slides=sorted((ROOT/'previews').glob('slide-*.png'))
assert len(slides)==len(story['slides'])
data=[]
for s,p in zip(story['slides'],slides):
    media=[m for m in manifest['slots'] if m['slide']==int(s['id']) and m['status'].startswith('completed')]
    data.append(dict(s,image=str(p.relative_to(ROOT)),media=media))
html=r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CAST · animated supplementary-video draft</title><style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#08111c;color:#f3f6fa}*{box-sizing:border-box}body{margin:0}main{max-width:1440px;margin:0 auto;padding:18px}header{display:flex;align-items:center;gap:12px;margin-bottom:12px;font-size:13px;color:#afbdd0}header strong{color:#42d7b4;font-size:20px}#stage{position:relative;background:#0d1827;aspect-ratio:16/9;width:100%;box-shadow:0 6px 32px #0005}#stage img{display:block;width:100%;height:100%;object-fit:contain}#stage video{position:absolute;display:block;pointer-events:none}nav{display:flex;align-items:center;gap:9px;flex-wrap:wrap;margin:14px 0}button,select{background:#16273b;color:#f3f6fa;border:1px solid #33455b;border-radius:6px;padding:9px 13px;font:inherit;cursor:pointer}button:hover{border-color:#42d7b4}#clock{font-variant-numeric:tabular-nums;color:#42d7b4;margin-left:auto}#notes{background:#16273b;border-radius:8px;padding:18px 24px;line-height:1.65;font-size:16px}#notes h2{font-size:18px;margin-top:0}#cue{color:#afbdd0;font-size:13px}.hint{font-size:12px;color:#afbdd0}a{color:#42d7b4}#scrub{width:100%;accent-color:#42d7b4}body.focus main{padding:0;max-width:none;height:100vh;display:grid;place-items:center}body.focus header,body.focus nav,body.focus .hint,body.focus #notes,body.focus #scrub{display:none}body.focus #stage{width:min(100vw,177.77778vh);height:auto;aspect-ratio:16/9}
</style></head><body><main><header><strong>CAST</strong><span>Animated draft · 96 seconds method + 60 seconds robot · 24 seconds available for incoming simulation footage</span></header>
<div id="stage"><img id="slide" alt="Presentation slide"></div><input id="scrub" type="range" min="0" max="__TOTAL__" step="0.1" value="0" aria-label="Presentation time">
<nav><button id="prev" aria-label="Previous slide">←</button><button id="play">Play __TIME__ draft</button><button id="next" aria-label="Next slide">→</button><select id="jump" aria-label="Choose slide"></select><button id="toggle">Hide notes</button><button id="focus">Presentation view</button><span id="clock"></span></nav>
<section id="notes"><h2 id="title"></h2><p id="script"></p><p id="cue"></p></section><p class="hint">←/→ slides · Space plays/pauses · Escape leaves presentation view. Method animations are complete; autonomous robot clips and recorded voiceover remain to be added. <a href="animations/index.html">Watch animations at full size</a> · <a href="voiceover_script.md">Spoken script</a> · <a href="voiceover_cue_sheet.md">Timed recording cues</a> · <a href="cast_video_slides.pptx">PowerPoint</a> · <a href="cast_video_slides.pdf">PDF</a></p></main>
<script>const slides=__SLIDES__;const TOTAL=__TOTAL__;let index=0,elapsed=0,playing=false,last=performance.now();const $=id=>document.getElementById(id);const fmt=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
slides.forEach((s,i)=>{let o=document.createElement('option');o.value=i;o.textContent=`${s.id} · ${s.section}`;$('jump').append(o)});
function sync(force=false){const local=elapsed-slides[index].start;document.querySelectorAll('#stage video').forEach(v=>{if(v.readyState>=1){const target=Math.max(0,Math.min(local,v.duration-0.01));if(force||Math.abs(v.currentTime-target)>.3)v.currentTime=target;if(playing&&local<v.duration){if(v.paused)v.play().catch(()=>{})}else v.pause()}})}
function show(i){index=Math.max(0,Math.min(slides.length-1,i));const s=slides[index];document.querySelectorAll('#stage video').forEach(v=>{v.pause();v.remove()});$('slide').src=s.image;$('slide').alt=s.title;$('title').textContent=`${fmt(s.start)}–${fmt(s.start+s.duration)} · ${s.title}`;$('script').textContent=s.narration;$('cue').textContent=s.media.length?'Playing: '+s.media.map(m=>m.id+' — '+m.title).join('; '):s.slots.length?'Autonomous footage reserved; current image is a labeled demonstration still.':'Static slide.';$('jump').value=index;for(const m of s.media){const v=document.createElement('video');v.muted=true;v.playsInline=true;v.preload='auto';v.src=m.filename;v.poster=m.poster;v.dataset.id=m.id;const [x,y,w,h]=m.playback_box_points;Object.assign(v.style,{left:x/960*100+'%',top:y/540*100+'%',width:w/960*100+'%',height:h/540*100+'%'});v.onloadedmetadata=()=>sync(true);$('stage').append(v)}clock();sync(true)}
function clock(){$('clock').textContent=`${fmt(elapsed)} / ${fmt(TOTAL)}`;$('scrub').value=elapsed}
function seek(t){elapsed=Math.max(0,Math.min(TOTAL,t));let i=slides.findIndex(s=>elapsed<s.start+s.duration);if(i<0)i=slides.length-1;if(i!==index)show(i);else sync(true);clock();last=performance.now()}
function go(i){seek(slides[Math.max(0,Math.min(slides.length-1,i))].start)}
function toggle(){if(elapsed>=TOTAL)seek(0);playing=!playing;$('play').textContent=playing?'Pause':'Play __TIME__ draft';sync(true);last=performance.now()}
$('prev').onclick=()=>go(index-1);$('next').onclick=()=>go(index+1);$('play').onclick=toggle;$('jump').onchange=e=>go(+e.target.value);$('scrub').oninput=e=>seek(+e.target.value);$('toggle').onclick=()=>{$('notes').hidden=!$('notes').hidden;$('toggle').textContent=$('notes').hidden?'Show notes':'Hide notes'};$('focus').onclick=()=>document.body.classList.add('focus');
window.onkeydown=e=>{if(['SELECT','INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();toggle()}if(e.key==='ArrowRight')go(index+1);if(e.key==='ArrowLeft')go(index-1);if(e.key==='Escape')document.body.classList.remove('focus')};
function tick(now){if(playing){elapsed=Math.min(TOTAL,elapsed+(now-last)/1000);let i=slides.findIndex(s=>elapsed<s.start+s.duration);if(i<0)i=slides.length-1;if(i!==index)show(i);sync();clock();if(elapsed>=TOTAL){playing=false;sync();$('play').textContent='Replay'}}last=now;requestAnimationFrame(tick)}show(0);requestAnimationFrame(tick);
</script></body></html>'''
html=html.replace('__SLIDES__',json.dumps(data).replace('</','<\\/')).replace('__TOTAL__',str(total)).replace('__TIME__',duration_label)
html=html.replace('__TOTAL__',str(total)).replace('__TIME__',duration_label)
(ROOT/'preview.html').write_text(html)
media=[m for m in manifest['slots'] if m['status'].startswith('completed')]
for m in media:
    m['filename']=os.path.relpath(ROOT/m['filename'],ROOT/'animations');m['poster']=os.path.relpath(ROOT/m['poster'],ROOT/'animations')
labels={'A01':'Watch the policy distribution shift','A02':'See the paired base and residual','A03':'Animated Figure 2: equations and clipping','A04':'Train the actor on fixed targets','A05':'See benchmark tasks and measured ablation results'}
for m in media:m['watch_title']=labels.get(m['id'],m['title'])
gallery=r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CAST · method animations</title><style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#0d1827;color:#f3f6fa}body{margin:0}main{max-width:1280px;margin:auto;padding:25px}h1{font-size:30px;margin:8px 0}p{color:#afbdd0;line-height:1.55}a{color:#42d7b4}nav{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}button{font:inherit;background:#16273b;color:#afbdd0;border:1px solid #33455b;border-radius:8px;padding:12px 16px;cursor:pointer}button.active{color:#42d7b4;border-color:#42d7b4}video{display:block;width:100%;aspect-ratio:16/9;background:#16273b;border-radius:10px}#brief{max-width:1000px}.tag{font-size:13px;letter-spacing:.08em;color:#42d7b4}footer{font-size:14px;margin-top:24px;color:#afbdd0}</style></head><body><main><div class="tag">CAST / METHOD ANIMATIONS</div><h1 id="title"></h1><p>Original, code-generated animations. Use the playback controls to pause, scrub, or view full screen.</p><nav id="clips"></nav><video id="video" controls playsinline preload="metadata"></video><p id="brief"></p><footer><a href="../preview.html">Timed slide preview</a> · <a href="README.md">Equations and reproduction notes</a> · <a href="https://rail.eecs.berkeley.edu/deeprlcourse-fa23/static/slides/lec-5.pdf">CS 285 teaching reference</a><p>A01–A04 are illustrative policy mechanics. A05 combines labeled task demonstrations with the submitted paper’s measured ablation data.</p></footer></main><script>
const clips=__CLIPS__;const v=document.getElementById('video');function pick(i,play=false){const c=clips[i];v.src=c.filename;v.poster=c.poster;document.getElementById('title').textContent=c.watch_title;document.getElementById('brief').textContent=c.brief;document.querySelectorAll('button').forEach((b,j)=>b.classList.toggle('active',i===j));if(play)v.play().catch(()=>{});history.replaceState(null,'','#'+c.id)}clips.forEach((c,i)=>{const b=document.createElement('button');b.textContent=c.id+' · '+c.slide_duration_seconds+'s';b.onclick=()=>pick(i,true);document.getElementById('clips').append(b)});let first=clips.findIndex(c=>'#'+c.id===location.hash);pick(Math.max(0,first));
</script></body></html>'''.replace('__CLIPS__',json.dumps(media).replace('</','<\\/'))
(ROOT/'animations/index.html').write_text(gallery)
print('Built timed animated slide player and full-size animation gallery.')
