# observation related
# seq_len: ${algo.chunk_size}
# obs_seq_len: ${algo.frame_stack}
# frame_stack: 1

suite_name: real
benchmark_name: debug_1
demos_per_env: null # load all demos
bimanual: false

task_embedding_format: ${algo.encoder.task_embedding_format}
img_height: 224
img_width: 224

# These have no meaning but need to be here for interpolation
n_tasks: 1
horizon: 300

shape_meta:
  actions: 
    actions: 7
  abs_actions: 
    abs_actions: 10
  rotation_rep_in: axis_angle
  rotation_rep_in_abs: rotation_6d
  rotation_rep_out: axis_angle
  observation:
    rgb:
      front_image:
        - 3
        - ${task.img_height}
        - ${task.img_width}
      wrist_image:
        - 3
        - ${task.img_height}
        - ${task.img_width}
    depth:
      front_depth:
        - 1
        - ${task.img_height}
        - ${task.img_width}
      wrist_depth:
        - 1
        - ${task.img_height}
        - ${task.img_width}
    lowdim:
      eef_pos: 3
      eef_ori: 3
      eef_openness: 1
  task:
    type: vector
    dim: 512


# build_dataset(data_prefix, benchmark_name, benchmark_name, seq_len, obs_seq_len, obs_modality):
dataset:
  _target_: imitation.envs.real.utils.build_dataset
  data_prefix: ${data_prefix}
  suite_name: ${task.suite_name}
  benchmark_name: ${task.benchmark_name}
  seq_len: ${algo.dataset.seq_len}
  frame_stack: ${algo.dataset.frame_stack}
  obs_seq_len: ${algo.dataset.obs_seq_len}
  shape_meta: ${task.shape_meta}
  load_obs: ${training.load_obs}
  load_image: ${algo.encoder.load_image}
  load_depth: ${algo.encoder.load_depth}
  task_embedding_format: ${task.task_embedding_format}
  n_demos: ${task.demos_per_env}
  hdf5_cache_mode: low_dim
  action_keys: 'actions/abs_actions'
  extra_obs_modality:
    low_dim: 
      - hand_mat
      - hand_mat_inv
      - front_extrinsic
      - wrist_extrinsic
      - front_intrinsic
      - wrist_intrinsic
  load_next_obs: ${algo.dataset.load_next_obs}

env_runner: null
  